searchengine=https://duckduckgo.com/?q=$1
spitefulness=9.7
; Comments are preceeded by a semicolon...
; Each section concerns an individual enemy
[larry]
fullname=Larry Doe
type=kindergarten bully
website=http://www.geocities.com/CapeCanaveral/11451

[davaeorn]
fullname=Davaeorn
type=evil wizard
outputdir=/hom/marijn/enemies/davaeorn

